spring.datasource.url=jdbc:postgresql://dpg-dal7jblbedkc73bi2u00-a.oregon-postgres.render.com:5432/splitflow_db_us7v?sslmode=require
spring.datasource.username=splitflow_db_us7v_user
spring.datasource.password=Tc8zlA4KtnrYK3DDuytAJLnmB6KoamEB
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,https://splitflow-frontend.onrender.com}