spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER:-}
spring.datasource.password=${DATABASE_PASSWORD:-}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Quitamos el dialecto explícito como sugería el warning de Hibernate
server.port=${PORT:8080}